CREATE TABLE ORGANIZATION(
  ORG_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(50) NOT NULL UNIQUE,
  DESCRIPTION VARCHAR(500) NOT NULL
);

CREATE TABLE COURSE(
  COURSE_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  ORGANIZATION_ID VARCHAR(16) NOT NULL ,
  AUTHOR VARCHAR(50)  NOT NULL ,
  TITLE VARCHAR(100)  NOT NULL ,
  DESCRIPTION VARCHAR(500) NOT NULL,
  VIEWS_NUMBER INT DEFAULT 0
);

CREATE TABLE EXAM(
  EXAM_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  COURSE_ID BIGINT NOT NULL ,
  TITLE VARCHAR(100) NOT NULL ,
  KNOWLEGDE_LEVEL VARCHAR(20)  NOT NULL ,
  APPROXIMATE_DURATION_MINS INT  NOT NULL
);
